int handleLogin();
int handleTransferedBytes();
int handleConcurrentConection();
int handleActiveTrasnformation();
int handleBufferSize();
int handleTransformationChange();
int handleTimeOut();
int handleQuit();
void printDatagram();